version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  pre_build:
    commands:
      - $(npm bin)/cypress verify
  build:
    commands:
      - $(npm bin)/cypress run --record --key d18e6be6-b228-47d3-a221-5c3a175d1248
